# Generated by Django 3.0 on 2024-12-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=300)),
                ('n', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=300)),
                ('uf', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('telefone_emergencia', models.CharField(max_length=100, null=True)),
                ('nascimento', models.CharField(max_length=100)),
                ('data_admissao', models.CharField(max_length=100)),
                ('data_demissao', models.CharField(max_length=100, null=True)),
                ('funcao', models.CharField(max_length=100)),
                ('carga_horaria', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100, null=True)),
                ('pis', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('manequim_farda', models.CharField(max_length=100)),
                ('escolaridade', models.CharField(max_length=100)),
                ('pai', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
                ('foto', models.FileField(null=True, upload_to='')),
                ('anexo_cpf', models.FileField(null=True, upload_to='')),
                ('anexo_rg', models.FileField(null=True, upload_to='')),
                ('curriculo', models.FileField(null=True, upload_to='')),
                ('carteira_trabalho', models.FileField(null=True, upload_to='')),
                ('comprovante_residencia', models.FileField(null=True, upload_to='')),
                ('exame_admissional', models.FileField(null=True, upload_to='')),
                ('exame_demissional', models.FileField(null=True, upload_to='')),
                ('banco', models.CharField(max_length=100, null=True)),
                ('agencia', models.CharField(max_length=100, null=True)),
                ('conta', models.CharField(max_length=100, null=True)),
                ('pix', models.CharField(max_length=100, null=True)),
                ('tipo_chave_pix', models.CharField(max_length=100, null=True)),
                ('inss', models.CharField(max_length=100, null=True)),
                ('fgts', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dissidio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dissidio', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('dissidio', models.FileField(upload_to='')),
                ('palavras_chave', models.CharField(max_length=500)),
            ],
        ),
    ]
