# Generated by Django 3.0 on 2024-12-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissidio',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
