# Generated by Django 3.0 on 2024-12-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0002_dissidio_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('n', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('data_abertura', models.CharField(max_length=100)),
            ],
        ),
    ]
