# Generated by Django 3.0 on 2024-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0003_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
