# Generated by Django 3.0 on 2024-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0004_entidade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcao', models.CharField(max_length=200)),
                ('dissidio_classe', models.CharField(max_length=200)),
                ('entidade', models.CharField(max_length=200)),
                ('valor_hora', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
