# Generated by Django 3.0 on 2025-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0005_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='bairro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='categoria_cnh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='cep_nascimento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='chegada_brasil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='cnh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='conjuge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='ctps',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='data_emissao_rg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='emissao_cnh',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='emissao_ctps',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='especializacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='municipio_nascimento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='nacionalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='orgao_emissor_rg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='reservista',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='secao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='titulo_eleitor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='uf_ctps',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='uf_nascimento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='zona',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
