# Generated by Django 3.0 on 2025-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0006_auto_20250108_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='tipo_vinculo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
