# Generated by Django 3.0 on 2025-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0007_colaboradores_tipo_vinculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='baixa_reservista',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='categoria_reservista',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='emissao_insc_categoria_prof',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='horario_trabalho',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='insc_categoria_prof_tipo_uf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='intervalo_jornada',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='lotacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='obs',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='salario_mensal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
