# Generated by Django 3.0 on 2025-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0008_auto_20250119_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='carteira_categoria_profissional',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='certidao_casamento_nascimento',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='certificado_escolaridade',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='cnh_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='conta_salario_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='ctps_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='curso_nacional_vigilante',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='curso_vigilante',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='reciclagem_curso_vigilante',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='reservista_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='titulo_eleitor_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
