# Generated by Django 3.0 on 2025-01-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0009_auto_20250119_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
