# Generated by Django 3.0 on 2025-07-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0010_colaboradores_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='sexo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
