# Generated by Django 3.0 on 2025-07-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0011_colaboradores_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='status_colaborador',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
