# Generated by Django 3.0 on 2025-07-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0012_colaboradores_status_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('nascimento', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
