# Generated by Django 3.0 on 2025-07-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0013_dependente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='certidao_nascimento_casamento',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
