# Generated by Django 3.0 on 2025-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0014_dependente_certidao_nascimento_casamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='cep',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependente',
            name='data_emissao_rg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependente',
            name='municipio_nascimento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependente',
            name='rg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependente',
            name='uf',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
