# Generated by Django 3.0 on 2025-07-31 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0015_auto_20250731_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependente',
            old_name='municipio_nascimento',
            new_name='municipio',
        ),
    ]
