# Generated by Django 3.0 on 2025-07-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0016_auto_20250731_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='bairro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dependente',
            name='logradouro',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
