# Generated by Django 3.0 on 2025-07-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0017_auto_20250731_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='n',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
