# Generated by Django 3.0 on 2025-07-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0018_dependente_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='vinculo_colaborador',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
