# Generated by Django 3.0 on 2025-08-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0020_usuariossistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('data_hora', models.CharField(max_length=200)),
                ('dados_post', models.CharField(max_length=200, null=True)),
                ('dados_pc_acesso', models.CharField(max_length=800)),
                ('ip', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=800)),
                ('tipo_acesso', models.CharField(max_length=10)),
                ('pagina', models.CharField(max_length=100)),
            ],
        ),
    ]
