# Generated by Django 3.0 on 2025-08-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0021_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='beneficio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='custo_viagem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='desconto_vale_transporte',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='descricao_beneficio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='descricao_devolucao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='horas_extra',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='quiquenio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='salario_familia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='vale_transporte',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
