# Generated by Django 3.0 on 2025-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0022_auto_20250804_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=200)),
                ('vinculo', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('usuario_cadastro', models.CharField(max_length=200, null=True)),
                ('obs', models.CharField(max_length=5000, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('entidade', models.CharField(max_length=200)),
                ('comprovante_pagamento', models.FileField(null=True, upload_to='')),
                ('nota_fatura', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PreCadastroContasPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_pre_cadastro', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('vinculo', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('obs', models.CharField(max_length=5000, null=True)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('entidade', models.CharField(max_length=200)),
                ('comprovante_pagamento', models.FileField(null=True, upload_to='')),
                ('nota_fatura', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
