# Generated by Django 3.0 on 2025-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0023_contaspagar_precadastrocontaspagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='nome_vinculo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
