# Generated by Django 3.0 on 2025-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0024_contaspagar_nome_vinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=200)),
                ('n', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('contrato_social', models.FileField(null=True, upload_to='')),
                ('cartao_cnpj', models.FileField(null=True, upload_to='')),
                ('data_abertura', models.CharField(max_length=200)),
                ('atuacao', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
