# Generated by Django 3.0 on 2025-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0026_centrocusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='centrodecusto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='precadastrocontaspagar',
            name='centrodecusto',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
