# Generated by Django 3.0 on 2025-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0027_auto_20251015_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=200)),
                ('nome_vinculo', models.CharField(max_length=200)),
                ('data_inicio', models.CharField(max_length=100)),
                ('data_fim', models.CharField(max_length=100)),
                ('contrato', models.FileField(null=True, upload_to='')),
                ('valor', models.CharField(max_length=200)),
                ('valor_atual_gasto', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
