# Generated by Django 3.0 on 2025-12-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0028_contratoreceita'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastrocontaspagar',
            name='contrato',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
