# Generated by Django 3.0 on 2025-12-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0029_precadastrocontaspagar_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='contrato',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
