# Generated by Django 3.0 on 2025-12-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0030_contaspagar_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(max_length=200)),
                ('nome_entidade', models.CharField(max_length=200)),
                ('nota_fiscal', models.FileField(null=True, upload_to='')),
                ('data', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('contrato', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
