# Generated by Django 3.0 on 2025-12-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0031_contasreceber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoreceita',
            name='valor_atual_recebido',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
