# Generated by Django 3.0 on 2025-12-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0032_contratoreceita_valor_atual_recebido'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('rua', models.CharField(max_length=200)),
                ('n', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('n_contrato', models.CharField(max_length=200)),
                ('servico_prestado', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
