# Generated by Django 3.0 on 2025-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0033_fornecedorpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedorpf',
            name='comprovante_residencia',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='fornecedorpf',
            name='rg',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
