# Generated by Django 3.0 on 2025-12-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0034_auto_20251230_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastrocontaspagar',
            name='fonte',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
