# Generated by Django 3.0 on 2025-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0035_precadastrocontaspagar_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='fonte',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
