# Generated by Django 3.0 on 2025-12-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0036_contaspagar_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasreceber',
            name='centro_custo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
