# Generated by Django 3.0 on 2025-12-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0037_contasreceber_centro_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=200)),
                ('conta', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=200)),
                ('apelido', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
