# Generated by Django 3.0 on 2025-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0038_contabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='conta_bancaria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='precadastrocontaspagar',
            name='conta_bancaria',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
