# Generated by Django 3.0 on 2025-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0039_auto_20251230_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasreceber',
            name='conta_bancaria',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
