# Generated by Django 3.0 on 2025-12-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0040_contasreceber_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='autorizacao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
