# Generated by Django 3.0 on 2026-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpo', '0041_contaspagar_autorizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
