from django.db import models

# Create your models here.
class PreCadastroContasPagar(models.Model):
    usuario_pre_cadastro = models.CharField(max_length=200)
    valor = models.CharField(max_length=200)
    vinculo = models.CharField(max_length=200)#Colaborador, Fornecedor, Movimentacao entre contas
    data = models.CharField(max_length=200)
    obs = models.CharField(max_length=5000, null=True)
    descricao = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    long = models.CharField(max_length=200)
    lat = models.CharField(max_length=200)
    entidade = models.CharField(max_length=200)
    #ARQUIVOS
    comprovante_pagamento = models.FileField(null=True)
    nota_fatura = models.FileField(null=True)#Nota fiscal, Fatura, Contracheque

class ContasPagar(models.Model):
    valor = models.CharField(max_length=200)
    vinculo = models.CharField(max_length=200)#Colaborador, Fornecedor, Movimentacao entre contas
    data = models.CharField(max_length=200)
    usuario_cadastro = models.CharField(max_length=200, null=True)
    obs = models.CharField(max_length=5000, null=True)
    descricao = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    long = models.CharField(max_length=200)
    lat = models.CharField(max_length=200)
    entidade = models.CharField(max_length=200)
    #ARQUIVOS
    comprovante_pagamento = models.FileField(null=True)
    nota_fatura = models.FileField(null=True)#Nota fiscal, Fatura, Contracheque

class Logs(models.Model):
    usuario = models.CharField(max_length=200)
    data_hora = models.CharField(max_length=200)
    dados_post = models.CharField(max_length=200, null=True)
    dados_pc_acesso = models.CharField(max_length=800)
    ip = models.CharField(max_length=20)
    endereco = models.CharField(max_length=800)
    tipo_acesso = models.CharField(max_length=10)
    pagina = models.CharField(max_length=100)

class UsuariosSistema(models.Model):
    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    permissao = models.CharField(max_length=200)

class Dependente(models.Model):
    nome = models.CharField(max_length=200)
    cpf = models.CharField(max_length=200)
    nascimento = models.CharField(max_length=200)
    rg = models.CharField(max_length=200, null=True)
    data_emissao_rg = models.CharField(max_length=200, null=True)
    municipio = models.CharField(max_length=200, null=True)
    cep = models.CharField(max_length=200, null=True)
    uf = models.CharField(max_length=200, null=True)
    bairro = models.CharField(max_length=200, null=True)
    n = models.CharField(max_length=200, null=True)
    logradouro = models.CharField(max_length=200, null=True)
    sexo = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    vinculo_colaborador = models.CharField(max_length=200, null=True)
    #arquivos
    certidao_nascimento_casamento = models.FileField(null=True)

class Funcao(models.Model):
    nome_funcao = models.CharField(max_length=200)
    dissidio_classe = models.CharField(max_length=200)
    entidade = models.CharField(max_length=200)
    valor_hora = models.CharField(max_length=200)
    status = models.CharField(max_length=200)

class Entidade(models.Model):
    razao_social = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=100)
    cep  = models.CharField(max_length=100)
    logradouro = models.CharField(max_length=100)
    n = models.CharField(max_length=100)
    municipio = models.CharField(max_length=100)
    uf = models.CharField(max_length=100)
    telefone = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    data_abertura = models.CharField(max_length=100)
    status = models.CharField(max_length=100, null=True)

class Dissidio(models.Model):
    nome_dissidio = models.CharField(max_length=200)
    cep = models.CharField(max_length=200)
    uf = models.CharField(max_length=200)
    dissidio = models.FileField()
    palavras_chave = models.CharField(max_length=500)
    status = models.CharField(max_length=300, null=True)

class Colaboradores(models.Model):
    #dados iniciais
    nome = models.CharField(max_length=200)
    email = models.CharField(max_length=100, null=True)
    cep = models.CharField(max_length=100)
    logradouro = models.CharField(max_length=300)
    n = models.CharField(max_length=100)
    municipio = models.CharField(max_length=300)
    bairro = models.CharField(max_length=300, null=True)
    uf = models.CharField(max_length=100)
    telefone = models.CharField(max_length=100)
    telefone_emergencia = models.CharField(max_length=100, null=True)
    nascimento = models.CharField(max_length=100)
    data_admissao = models.CharField(max_length=100)
    data_demissao = models.CharField(max_length=100, null=True)
    funcao = models.CharField(max_length=100)
    carga_horaria = models.CharField(max_length=100)
    cpf = models.CharField(max_length=100)
    rg = models.CharField(max_length=100, null=True)
    data_emissao_rg = models.CharField(max_length=100, null=True)
    orgao_emissor_rg = models.CharField(max_length=100, null=True)
    pis = models.CharField(max_length=100)
    estado_civil = models.CharField(max_length=100)
    manequim_farda = models.CharField(max_length=100)
    escolaridade = models.CharField(max_length=100)
    especializacao = models.CharField(max_length=100, null=True)
    pai = models.CharField(max_length=100)
    mae = models.CharField(max_length=100)
    foto = models.FileField(null=True)
    nacionalidade = models.CharField(max_length=100, null=True)
    chegada_brasil = models.CharField(max_length=100, null=True)
    municipio_nascimento = models.CharField(max_length=100, null=True)
    uf_nascimento = models.CharField(max_length=100, null=True)
    cep_nascimento = models.CharField(max_length=100, null=True)
    emissao_ctps = models.CharField(max_length=100, null=True)
    uf_ctps = models.CharField(max_length=100, null=True)
    ctps = models.CharField(max_length=100, null=True)
    reservista = models.CharField(max_length=100, null=True)
    titulo_eleitor = models.CharField(max_length=100, null=True)
    zona = models.CharField(max_length=100, null=True)
    secao = models.CharField(max_length=100, null=True)
    cnh = models.CharField(max_length=100, null=True)
    emissao_cnh = models.CharField(max_length=100, null=True)
    categoria_cnh = models.CharField(max_length=100, null=True)
    conjuge = models.CharField(max_length=100, null=True)
    tipo_vinculo = models.CharField(max_length=100, null=True)
    baixa_reservista = models.CharField(max_length=100, null=True)
    categoria_reservista = models.CharField(max_length=100, null=True)
    salario_mensal = models.CharField(max_length=100, null=True)
    insc_categoria_prof_tipo_uf = models.CharField(max_length=100, null=True)
    lotacao = models.CharField(max_length=100, null=True)
    emissao_insc_categoria_prof = models.CharField(max_length=100, null=True)
    horario_trabalho = models.CharField(max_length=100, null=True)
    intervalo_jornada = models.CharField(max_length=100, null=True)
    sexo = models.CharField(max_length=100, null=True)
    status_colaborador = models.CharField(max_length=100, null=True)
    obs = models.CharField(max_length=100000, null=True)
    #documentos
    anexo_cpf = models.FileField(null=True)
    anexo_rg = models.FileField(null=True)
    curriculo = models.FileField(null=True)
    carteira_trabalho = models.FileField(null=True)
    comprovante_residencia = models.FileField(null=True)
    exame_admissional = models.FileField(null=True)
    exame_demissional = models.FileField(null=True)
    titulo_eleitor_file = models.FileField(null=True)
    carteira_categoria_profissional = models.FileField(null=True)
    certificado_escolaridade = models.FileField(null=True)
    reservista_file = models.FileField(null=True)
    certidao_casamento_nascimento = models.FileField(null=True)
    ctps_file = models.FileField(null=True)
    conta_salario_file = models.FileField(null=True)
    cnh_file = models.FileField(null=True)
    curso_vigilante = models.FileField(null=True)
    reciclagem_curso_vigilante = models.FileField(null=True)
    curso_nacional_vigilante = models.FileField(null=True)
    status = models.CharField(max_length=300, null=True)
    #dados bancarios
    banco = models.CharField(max_length=100, null=True)
    agencia = models.CharField(max_length=100, null=True)
    conta = models.CharField(max_length=100, null=True)
    pix = models.CharField(max_length=100, null=True)
    tipo_chave_pix = models.CharField(max_length=100, null=True)
    #fiscais
    inss = models.CharField(max_length=100, null=True)
    fgts = models.CharField(max_length=100, null=True)
    vale_transporte = models.CharField(max_length=100, null=True)
    desconto_vale_transporte = models.CharField(max_length=100, null=True)
    salario_familia = models.CharField(max_length=100, null=True)
    horas_extra = models.CharField(max_length=100, null=True)
    beneficio = models.CharField(max_length=100, null=True)
    descricao_beneficio = models.CharField(max_length=500, null=True)
    custo_viagem = models.CharField(max_length=100, null=True)
    descricao_devolucao = models.CharField(max_length=100, null=True)
    quiquenio = models.CharField(max_length=100, null=True)